apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
  label: 
    app: techtrends
spec:
  selector:
    app: techtrends
  ports:
    - name: techtrends-service
      targetPort: 3111
      port: 4111
      protocol: TCP
  type: ClusterIP